image: node:10.16.3 # change to match your project's node version

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf build
  - CI=false npm install

pages:
  stage: deploy
  script:
    - CI=false npm run build
    - mkdir .public
    - cp -r * .public
    - mv .public public

  artifacts:
    paths:
      - public/public
  only:
    - master
